### PR TITLE
Add hostname/IP address/Pi model info to nabweb system info page.

### PR DESCRIPTION
**Pull request by f-laurens**
Related to #15.
Add hostname and IP address to OS section and Rapberry PI model to hardware section of nabweb 'System Information' page.

### CODE REVIEW

**Comment by f-laurens** [comment]
system-info

**Comment by mehdichaouch** [comment]
@f-laurens I think before starting to fix an issue would be nice to declare that you want to work on it and for @nabaztag2018 to assign the issue, like that we all know who work on what.

I said that because I ask here https://github.com/nabaztag2018/pynab/issues/15#issuecomment-827471868 to know what have to be done, with goal to probably work on.

Last, thanks @f-laurens 🚀

**Comment by mehdichaouch** [comment]
@f-laurens ok if you don't want to wait for the maintainer feedack and assignation, that's not a big deal for me.
But respectfully could you at least say in the issues when you take it?

**Comment by f-laurens** [comment]
> But, respectfully, could you at least say in the issues when you take it?

Hmm... Respectfully again, this would be relevant for a **simple** issue (with a 1 to 1 Issue to PR mapping).
But here, given the scope of issue #15, this is not: this PR does not pretend to **fix** it, it is only noted as **related** to it (as was the case for PRs #126, #185...: I'm pretty sure a number of atomic PRs may still be created to address it).

**Pull request merged**
