### PR TITLE
Revamp system information and upgrade pages

### PR DESCRIPTION
**Pull request by f-laurens**
System information page:
- add kernel build# to OS version information;
- retrieve kernel information using `platform` module, rather than `uname` command;
- add wireless network (using `iwgetid` command);
- add help links.

Upgrade page:
- improve(?) wording/translations.
- correct help link for Git.

### CODE REVIEW

**Comment by nabaztag2018** [comment]
Hello, could you keep the regular BOLD instead of BOLD+Orange ? Thanks!
Capture d’écran 2021-06-01 à 10 15 05

**Comment by f-laurens** [comment]
> Hello, could you keep the regular BOLD instead of BOLD+Orange ? Thanks!

Will do. Too bad you merged the PR... can you re-open it?

**Comment by nabaztag2018** [comment]
I can revert it but not sure I can re-open it.

**Comment by f-laurens** [comment]
> I can revert it but not sure I can re-open it.

I force-pushed the change to my branch. Can you revert the PR?

**Comment by f-laurens** [comment]
Waiting for merge of #262 before resubmitting amended version of #259... Too bad it was merged too soon :-(

**Pull request merged**
