### PR TITLE
Add favicon

### PR DESCRIPTION
**Pull request by mehdichaouch**
Fix this error:

```
pi@nabaztag:~/pynab/nabweb/static $ tail -f /var/log/daemon.log
Apr 25 19:02:25 nabaztag gunicorn[576]: Not Found: /favicon.ico
```

favicon

### CODE REVIEW

**Comment by nabaztag2018** [comment]
Hello, there's a requirement error on pytz. I just merged a new fix, maybe can you update your repository and push the PR again ?

**Comment by mehdichaouch** [comment]
@nabaztag2018 you merged PR #181 , but Build #779 in Travis CI is still in error !
That's not a problem ?

**Comment by nabaztag2018** [comment]
Nope :-)

**Comment by f-laurens** [comment]
@mehdichaouch:
>  you merged PR #181 , but Build #779 in Travis CI is still in error ! That's not a problem ?

May be you should cherry-pick the commits PR #181 into your https://github.com/mehdichaouch/pynab/tree/favicon branch and push it again?

**Comment by f-laurens** [comment]
@nabaztag2018:
> As I see bug came from [wm8960 driver](https://travis-ci.org/github/nabaztag2018/pynab/builds/768340541#L11182) and there is fix is here : [pguyot/wm8960#9](https://github.com/pguyot/wm8960/pull/9) from @f-laurens, so just need to be tested/merged by @pguyot 🤔

One has to be cautious here: my fix to the driver makes it compatible with recent (>= 5.1.0.11) versions  of the Raspberry Pi kernel, but as a consequence makes it incompatible with previous versions....
So integrating my fix implies using a Raspberry Pi OS image with a recent kernel.
This raises the issue of the implicit dependency between pynab and the drivers (where the pynab install/upgrade script always tries to pull the latest version of the drivers).

Maybe this means it would be high time to publish a new (v0.8.5) release of Pynab, based on the latest Raspberry Pi OS image (and integrating the latest and greatest PRs 😉)...

**Comment by mehdichaouch** [comment]
@f-laurens I rebased my PR on master 😃.

@nabaztag2018 this one is ready for reviewing 💚.

**Comment by nabaztag2018** [comment]
Today is my 🎂, it's merge day 🥳

**Comment by mehdichaouch** [comment]
### **YEAH 🎉 🥂** 

tenor

**Comment by mehdichaouch** [comment]
> it's merge day 🥳

@nabaztag2018 maybe it'll be also a release day? 🤩

**Comment by f-laurens** [comment]
@mehdichaouch:
> maybe it'll be also a release day? 🤩

Hmmm.... #186 and https://github.com/pguyot/wm8960/issues/8 will need to be handled first...
Also, maybe  https://github.com/nabaztag2018/pynab/pull/177#discussion_r619195692 should also be fixed... 🤨

**Pull request merged**
