### PR TITLE
Correction select list width

### PR DESCRIPTION
**Pull request by a-mnt**
Natural led pulse + originales ear position

### CODE REVIEW

**Comment by f-laurens** [comment]
Resolves #150

**Comment by a-mnt** [comment]
This correction don't working with Safari on iOS 14. #150

**Comment by f-laurens** [comment]
> This correction don't working with Safari on iOS 14. #150
Well... It works nicely for me: dropdown buttons display correctly.

**Comment by mehdichaouch** [comment]
What'up about this PR? Did you need mode tester?

**Comment by f-laurens** [comment]
> Did you need mode tester?

What do you mean by 'mode tester'?
My personal experience is that PR #164 works nicely to fix the select list width issue with nabweb dropdown buttons.

**Comment by f-laurens** [comment]
To be closed as duplicate since PR #164 is now merged ?..

**Comment by nabaztag2018** [comment]
Thanks a lot @a-mnt ! (It has been merge through PR #164)

**Pull request closed without merging**
