### PR TITLE
Docker-based environment: Cleanup

### PR DESCRIPTION
**Pull request by f-laurens**
- align `Docker/nab/requirements.txt` with `requirements.txt`;
- make sure piwheels is enabled for pip install;
- use migration script to also compile localization messages;
- fix `nabd` so that NabIO is non-virtual only on armv6l.

### CODE REVIEW

**Comment by f-laurens** [comment]
Question @pguyot:
in `NabIOVirtual`, `has_rfid` returns `True`. Shouldn't it be `False`?

**Comment by f-laurens** [comment]
Another question:
Is there a compelling reason for having a container for each service?
One could think of a simpler model with 3 containers:
- `db`:  same as current model;
- `migrate`: same as current model;
- `pynab`: all Pynab services: nabd running with NabIOVirtual interface, the nab.*d services, and web interface WSGI.

**Comment by nguillaumin** [comment]
One service per container is the "Docker Way" 😉 more exactly it's one *process* per container. If you want to run multiple ones in a single container then you need something on top to start and manage them (some sort of init daemon) which adds some complexity. You would also loose some benefits like separated logging per container, etc.

A container being just a process for the kernel, there's no real advantage in grouping them (it's not like a VM where there's the overhead of the guest OS).

**Comment by f-laurens** [comment]
> One service per container is the "Docker Way" 😉 more exactly it's one _process_ per container.

Ok; I got it.
But in the case of Pynab, it looks like this has some practical drawbacks, especially for an environment intended for development, not production:

- Multiplication of identical images: slower deployment, and multiplication of resources on host system;
- Complexity:
> If you want to run multiple ones in a single container then you need something on top to start and manage them (some sort of init daemon) which adds some complexity;

  Having a single daemon (script) that does the inits and runs/manages the Pynab services may end up begin simpler than the stuff currently needed to achieve synchronization between containers;

- Logging:
> You would also lose some benefits like separated logging per container, etc.

   Not really an issue since logs for Pynab services are easily differentiated.

I think I will propose my 2 containers model as a PR for review.

**Comment by f-laurens** [comment]
I have proposed my implementation of the 2 containers model in #289.

**Comment by f-laurens** [comment]
Closing this PR which is now useless since PR #289 has been merged.

**Pull request closed without merging**
