### PR TITLE
Add help page documenting air quality visual animations

### PR DESCRIPTION
**Pull request by f-laurens**
Related to #16 and #255.
In the same way as PR #248 for the Weather widget, this PR adds a page that documents the air quality visual animations and is linked from the _visual animation_ reference in the Air quality widget.
Also change class of  the _visual animation_ references to `help-link` for both widgets and turn  _ask your rabbit_ references into help links to speech recognition help.

### CODE REVIEW

**Comment by f-laurens** [comment]
At this point, this PR is **still work in progress**:
the GIFs showing the animations are currently **dummy** placeholders, pending the availabilty of the **real** ones (see https://github.com/nabaztag2018/pynab/issues/16#issuecomment-847845667).

**Comment by mehdichaouch** [comment]
When you are in DRAFT/WIP, you can use the link in right column:
wip

**Comment by f-laurens** [comment]
> When you are in DRAFT/WIP, you can use the link in right column:

If you so desire, **Master**, but not really a draft, since it has been tested,  just WIP since it only need the finally GIF resources before merge.

**Comment by mehdichaouch** [comment]
> If you so desire, **Master**, but not really a draft, since it has been **tested** (not everyone does this...) , just WIP since it only needs the final GIF resources before merge.

Of course sir 🧐, it's not a **_DRAFT_** it's a **_WIP_** 😉
wip

**Comment by f-laurens** [comment]
> Of course sir , it's not a **_DRAFT_** it's a **_WIP_** , sorry for saying draft

can we do without this continuous trolling?..

**Comment by f-laurens** [comment]
> https://github.com/nabaztag2018/pynab/pull/252#issuecomment-851258600
Thanks. I'll convert the Air quality MP4s to GIF and use them to update this PR.

**Comment by f-laurens** [comment]
PR has been updated with GIF resources for the real animations.
It is now ready for merge.

**Pull request merged**
