### PR TITLE
Play a sound after the first boot #59

### PR DESCRIPTION
**Pull request by BoOsteous**
Hi, 

I propose this first contribution from my side to add a sound after boot.

In this version, the sound will be played after each boot (idle or sleep), in FR.
The sound is taken from a folder where i only put one sound in FR for now.

Related to #59

### CODE REVIEW

**Comment by f-laurens** [comment]
Resolves #59 .

**Comment by f-laurens** [comment]
See alternative implementation in PR #180.

**Comment by f-laurens** [comment]
To be closed as duplicate since PR #180 is now merged ?..

**Comment by nabaztag2018** [comment]
Thanks a lot @BoOsteous! this has been added in PR #180

**Pull request closed without merging**
