### PR TITLE
First implementation for funny ASR https://github.com/nabaztag2018/pynab/issues/60

### PR DESCRIPTION
**Pull request by clouetb**
Hi,

I tried to implement your proposal for funny ASR.

Let me know if it needs some rework to fit your taste.

I did not create a new service because the pi zero seems to have a hard time processing speech recognition.

Maybe I should have refactored the nabsurprised a little bit more, but I was eager to get it done quickly.

Anyway, thank you for reviving Nabaztag !

Kind regards,

Benoît

### CODE REVIEW

**Comment by pguyot** [comment]
> I did not create a new service because the pi zero seems to have a hard time processing speech recognition.

In fact, we should avoid having too many services, as each Python interpreter takes 20MB of RAM. So it's indeed best to include this in nabsurprised.
I created a new easter egg based on "anniversaire.wav" to get the rabbit to sing Happy Birthday (my kids and their friends loved it), will wait until your PR is merged to commit it.

Also, you refer to bug #79 and I might have a fix within few days.

**Comment by pguyot** [comment]
Thanks!
Forgot to mention that the new model should be added to installation & upgrade scripts, will commit this separately.

**Comment by clouetb** [comment]
> > I did not create a new service because the pi zero seems to have a hard time processing speech recognition.
> 
> In fact, we should avoid having too many services, as each Python interpreter takes 20MB of RAM. So it's indeed best to include this in nabsurprised.

Thank you for your help!

Forgive my question, but, what is the rationale behind splitting nabd and the other services considering how small the processing made in the services is? Is it to comply with the Django Architecture (which I don't know)?

**Comment by pguyot** [comment]
It's mostly for process isolation, to make sure services are independent and crashes of a service does not impact nabd or other services (which did happen and will happen again). Systemd is used as a process supervisor, restarting crashing services.

**Comment by 232enero** [comment]
I've just tested it, so great! Thanks thanks thanks Benoit !

**Pull request merged**
