### PR TITLE
Default values fix for Weather and Air quality

### PR DESCRIPTION
**Pull request by omevel**
Could not find a way to test this without having a new image generated. Help ! :-)

### CODE REVIEW

**Comment by mrcroupotin** [comment]
I definitively prefer Concarneau to Paris for the default location ;-)

I do not know much Python but the syntax below looks very fuzzy : null ='...'
Are you sure of it?
field=models.TextField(null='Concarneau - Bretagne (29) - FR')

**Comment by omevel** [comment]
oops, it is, i thought i pushed this fix but it seems not.... sorry

**Comment by f-laurens** [comment]
I strongly object to **Concarneau (29)** as default location for weather forecast :-(
**Cherbourg (50)** would be a more acceptable choice ;-)

Having **Paris (75)** as default seems in the only logical choice for preserving Pynab's international fame...

**Review by f-laurens — COMMENTED** [review]
Why 2 migrations for `nabweatherd`?
The lastest one (`0013`) (to be renamed as `0012`) should be enough?

**Comment by f-laurens** [comment]
Why several (redundant?) migrations (0011,0012,0013,0014) for  `nabweatherd`? One should be enough.

**Comment by omevel** [comment]
Ok got it, I'm closing this PR and will try again :-)

**Pull request closed without merging**
