### PR TITLE
Review/amend logging calls level. Set default logging level to INFO

### PR DESCRIPTION
**Pull request by f-laurens**
Related to #223.
Review/amend logging calls level to reduce log verbosity:
- a few `debug` logs of informative value have been promoted to `info` level;
- a number of `info` logs only of debug value have been demoted to `debug` level.
This allows setting default logging level to `INFO` and have less verbose, while still informative, logs.

Moreover, default level can now be set through `LOGLEVEL` environment variable.
This is done on a daemon basis, through a configuration file used by the daemon's service; by default all configuration files are linked to nabd's configuration (`/home/pi/pynab/nabd/nabd.conf`), which allows changing log level for all daemons by changing only this file.

### CODE REVIEW

**Comment by f-laurens** [comment]
**Note:** when testing this PR, **don't forget** to run the `upgrade.sh` script, in order to setup the new daemon service files.

**Comment by omevel** [comment]
Note to the PR testing, when I test a PR with the procedure described in https://github.com/nabaztag2018/pynab/blob/master/CONTRIBUTING.md i get as a result of bash upgrade.sh 👍 

+ git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> pr/266

++ s=1
++ echo 'upgrade.sh: Error on line 38: git pull'
upgrade.sh: Error on line 38: git pull
++ exit 1

Any ideas ?

**Comment by f-laurens** [comment]
> when I test a PR with the procedure described in https://github.com/nabaztag2018/pynab/blob/master/CONTRIBUTING.md i get as a result of bash upgrade.sh ...

Since this is not specifically related to this PR, this thread should rather be moved to a (new) Discussion...

**Comment by omevel** [comment]
ok no problem, i will merge your PR to test it

**Comment by f-laurens** [comment]
> ok no problem, i will merge your PR to test it

Hmmm... D**on't do this**!: I don't want to have (again) to make a new PR if this one is merged too soon...

**Comment by omevel** [comment]
Ok, I'll wait for another one to test this then!

**Comment by f-laurens** [comment]
What was again this problem you had with `upgrade.sh`? (you deleted your post...)

**Comment by omevel** [comment]
Hello !

Seems i still get debug message from nabairqualityd :
 
==> /var/log/nabairqualityd.log <==
INFO 2021-06-03 09:45:26,565 compute_next reason == BOOT
INFO 2021-06-03 09:45:26,615 fetch_info_data type = info
DEBUG 2021-06-03 09:45:26,660 Starting new HTTP connection (1): api.waqi.info:80
DEBUG 2021-06-03 09:45:30,340 http://api.waqi.info:80 "GET /feed/geo:48.86;2.34444/?token=4cf7f445134f3fb69a4c3f0e5001e507a6cc386f HTTP/1.1" 200 None
DEBUG 2021-06-03 09:45:30,358 {'status': 'ok', 'data': {'aqi': 50, 'idx': 5171, 'attributions': [{'url': 'http://www.atmo-hdf.fr/', 'name': "Atmo Hauts de Frane - Qualité de l'air en Picardie (Somme, Aisne, Oise)", 'logo': 'France-AtmoPicardie.png'}, {'url': 'https://waqi.info/', 'name': 'World Air Quality Index Project'}], 'city': {'geo': [49.259552777778, 2.4743972222222], 'name': 'Faiencerie Creil, Picardie, France', 'url': 'https://aqicn.org/city/france/picardie/faiencerie-creil'}, 'dominentpol': 'pm25', 'iaqi': {'h': {'v': 95.7}, 'no2': {'v': 6.8}, 'o3': {'v': 8.3}, 'p': {'v': 1018.7}, 'pm10': {'v': 17}, 'pm25': {'v': 50}, 'so2': {'v': 0.9}, 't': {'v': 20}, 'w': {'v': 0.6}, 'wg': {'v': 0.3}}, 'time': {'s': '2021-06-03 07:00:00', 'tz': '+02:00', 'v': 1622703600, 'iso': '2021-06-03T07:00:00+02:00'}, 'forecast': {}, 'debug': {'sync': '2021-06-03T16:35:43+09:00'}}}
DEBUG 2021-06-03 09:45:30,362 Air quality indices from aqicn.org for Faiencerie Creil, Picardie, France are: AQI=50 PM25=50 - selected index: pm25
DEBUG 2021-06-03 09:45:30,431 process nabd packet: {'status': 'ok', 'type': 'response'}
INFO 2021-06-03 09:45:30,503 compute_next saved_date=None
INFO 2021-06-03 09:45:30,545 reason = Reason.PERFORMANCE_PLAYED
INFO 2021-06-03 09:45:30,546 sleep_amount = 3599.960433

**Comment by f-laurens** [comment]
> Seems i still get debug message from nabairqualityd :

Are you on the correct branch? Has nabairqualityd been restarted?
With the new code, the start message for a daemon should be as such, stating the log level:
`INFO 2021-06-03 08:18:07,425 nabairqualityd started with log level INFO`

**Comment by omevel** [comment]
That's what I have for the other services. I'm going to retry the instructions on the CONTRIBUTING.md

**Comment by f-laurens** [comment]
> That's what I have for the other services. I'm going to retry the instructions on the CONTRIBUTING.md

`bash install.sh --upgrade` (see latest CONTRIBUTING.md in #264 )
Or you can just restart the service by hand:  `sudo systemctl restart nabairqualityd`

**Comment by omevel** [comment]
I get that now ->  ! [rejected]        refs/pull/266/head -> pr/266  (non-fast-forward)

I think the whole test-a-PR-procedure needs to be reworked. Not related to this PR.

**Comment by f-laurens** [comment]
> I get that now -> ! [rejected] refs/pull/266/head -> pr/266 (non-fast-forward)

have you tried deleting your local `pr/266 `branch altogether and redoing the whole procedure from the start?

> I think the whole test-a-PR-procedure needs to be reworked. Not related to this PR.

Indeed...

**Comment by omevel** [comment]
> > I think the whole test-a-PR-procedure needs to be reworked. Not related to this PR.
> 
> Indeed... It might be better to just refer to the official GitHub documentation for the Git related operations:
> https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

Followed these instructions and it's working now. 
(could you update the CONTRIBUTING.md in your other PR ?)

**Comment by f-laurens** [comment]
> (could you update the CONTRIBUTING.md in your other PR ?)

Done in PR #264.

**Pull request merged**
