### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by pguyot**

### CODE REVIEW

**Comment by f-laurens** [comment]
Shouldn't the `create-image` script be cleaned up too?
It looks largely obsolete...

**Comment by pguyot** [comment]
Thanks. I meant to delete it as well, especially since qemu-wrapper.c is now gone, as logic has been moved to https://github.com/pguyot/arm-runner-action

**Comment by f-laurens** [comment]
Thanks for https://github.com/nabaztag2018/pynab/pull/216.
In the same vein, is `install_kaldi.sh` still used somewhere (since `install.sh` does the job)?

**Comment by pguyot** [comment]
It was used in CI script. Removed in #219

**Pull request merged**
