### PR TITLE
👷 Add Pull Request auto labelling

### PR DESCRIPTION
**Pull request by mehdichaouch**
Based on: https://github.com/actions/labeler

### CODE REVIEW

**Comment by f-laurens** [comment]
@mehdichaouch @omevel: what is this mess with this _Pull Request Labeler_?
(see https://github.com/nabaztag2018/pynab/pull/250/checks?check_run_id=2674876798)
Was it tested before merge?

**Comment by mehdichaouch** [comment]
I just push a fix.
I tested the workflow in my fork, but after test I change labels introducing this typo bug.
Sorry PR fix #251

**Comment by omevel** [comment]
It does not seem to pass the test. Can you check ? Thanks !

**Comment by f-laurens** [comment]
@omevel: can you just disable this workflow in GitHub Actions till the problem is fixed?

**Comment by omevel** [comment]
done

**Comment by mehdichaouch** [comment]
> @omevel: can you just disable this workflow in GitHub Actions till the problem is fixed?

Respectfully @f-laurens there is no emergecy PR to be merge so why asking to disable it?

**Comment by f-laurens** [comment]
> so why asking to disable it?

Because a workflow that doesn't work is a **real nuisance** and a loss of time for everyone, that's all...

**Pull request merged**
