### PR TITLE
Revamp system information and upgrade pages

### PR DESCRIPTION
**Pull request by f-laurens**
System information page:
- add kernel build# to OS version information;
 -retrieve kernel information using `platform` module, rather than `uname` command;
 - add wireless network (using `iwgetid` command);
 - add help links.
 
Upgrade page:
 - improve(?) wording/translations.
 - correct help link for Git.

### CODE REVIEW

**Comment by f-laurens** [comment]
PR #259 amended...

**Comment by nabaztag2018** [comment]
Weird, I have this mix of english+french ->
Capture d’écran 2021-06-01 à 15 16 20

**Comment by f-laurens** [comment]
> Weird, I have this mix of english+french

Let me check...

**Comment by nabaztag2018** [comment]
Probably! I manually launch compilemessages and it's OK now.

**Pull request merged**
