### PR TITLE
Improve wording with better html

### PR DESCRIPTION
**Pull request by mehdichaouch**
Make a better rendering in text message with the right html code, to get things like this:

> wording

If it's necessary to update the MO file, I need advice to do it. Thx 🙏 .

### CODE REVIEW

**Comment by mehdichaouch** [comment]
I need advice to generate/update the MO file.

**Comment by f-laurens** [comment]
> If it's necessary to update the MO file, I need advice to do it. Thx 🙏 .

For each impacted `nabxxd`,  executing the following commands from the `pynab/nabxxd` directory should do the trick:
`../venv/bin/django-admin makemessages -l fr_FR`
(to update `django.po` file)
` ../venv/bin/django-admin compilemessages -l fr_FR`
(to regenerate `django.mo` file)

**Comment by mehdichaouch** [comment]
I rebased my PR on master 😃.

@nabaztag2018 this one is ready for reviewing 💚.

**Comment by f-laurens** [comment]
@mehdichaouch , @nabaztag2018 :
Have you tested this with the french locale?
Maybe I'm missing something here, but it looks like `<q>` tags in messages prevents matching/substitution of the localized version in the web interface... ☹️
The displayed message is then the original (english) one, rather than the localized (french) one. For example:
`La qualité de l'air est donnée en fonction de votre adresse IP. Vous pouvez sélectionner le type d'information que vous souhaitez utiliser : Index agrégé ou simplement les particules fines (PM 2.5).` **good**

`You can also ask your rabbit by saying such things as "What is the air quality today ?"` **bad**

**Comment by f-laurens** [comment]
@mehdichaouch, @f-laurens:
According to https://stackoverflow.com/questions/32830117/can-django-trans-tags-include-html-tags, this is a restriction of the Django trans tag, which should not include HTML tags...

**Comment by mehdichaouch** [comment]
Sorry for this bug 😕.

I've done changes here https://github.com/mehdichaouch/pynab/commit/1ad79393d5049ac6ad0e862a3484d1303cd1afb8, but I get errors when I run `./venv/bin/django-admin makemessages -l fr_FR` from my Nabaztag in my branch.
I have also tried without my changes and I also get an error, so help is required (I do Python only since 2 weeks on my Nabaztag) to understand this. Thx.

```bash
./venv/lib/python3.7/site-packages/zipp-0.6.0.dist-info/top_level.txt.py
./venv/lib/python3.7/site-packages/zipp.py
./venv/lib/python3.7/site-packages/plac_core.py:179: warning: 'msgid' format string with unnamed arguments cannot be properly localized:
                                                              The translator cannot reorder the arguments.
                                                              Please consider using a format string with named arguments,
                                                              and a mapping instead of a tuple for the arguments.
./venv/lib/python3.7/site-packages/plac_core.py:323: warning: 'msgid' format string with unnamed arguments cannot be properly localized:
                                                              The translator cannot reorder the arguments.
                                                              Please consider using a format string with named arguments,
                                                              and a mapping instead of a tuple for the arguments.
xgettext: ./venv/lib/python3.7/site-packages/scipy/io/matlab/tests/test_mio.py:1: Unknown encoding "latin-1". Proceeding with ASCII instead.
xgettext: Non-ASCII string at ./venv/lib/python3.7/site-packages/scipy/io/matlab/tests/test_mio.py:1142.
          Please specify the source encoding through --from-code or through a comment
          as specified in http://www.python.org/peps/pep-0263.html.```

**Comment by mehdichaouch** [comment]
Finally I understand my error, when running `../venv/bin/django-admin makemessages -l fr_FR` I was not in the folder of each `nab___d` 🙃, but I don't see changes in my setting pages. Help would be appreciate https://github.com/mehdichaouch/pynab/commit/1ad79393d5049ac6ad0e862a3484d1303cd1afb8.

**Pull request merged**
